'use client'
import { useEffect } from "react";
import { useRouter } from "next/router";
import Menu from "@/components/menu";
import Head from 'next/head'
import Detalhe from "@/components/detalhes";
import { useState } from "react";
import  'bootstrap/dist/css/bootstrap.min.css' ;

export default function use (){

    return(
        <>
      <Head>
        <title>Opyt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
      <Detalhe/>
  
    </>
    )
}