import Head from 'next/head'
import { Inter } from 'next/font/google'
import  'bootstrap/dist/css/bootstrap.min.css' ;
import "@/styles/Home.module.css"
import Menu from '@/components/menu';  
import AdOrigem from '@/components/origem';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Opyt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <AdOrigem/>
    </>
  )
}
